version: "3.8"
services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "8080:8080"

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    ports:
      - "8090:8090"
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8080

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://nginx/api 

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - orchestrator
      - agent
      - frontend