FROM golang:1.23.1-alpine AS builder
WORKDIR /agent

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o agent ./cmd/agent

FROM alpine:latest
WORKDIR /agent
COPY --from=builder /agent/agent .
EXPOSE 8090
CMD ["./agent"]