version: "3.8"
services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "8080:8080"
      - "8090:8090"

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8080
      - GRPC_HOST=orchestrator
      - GRPC_PORT=8090
    depends_on:
      - orchestrator
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      - orchestrator