FROM golang:1.23.1-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o orchestrator ./cmd/orchestrator

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/orchestrator .
EXPOSE 8080
CMD ["./orchestrator"]