// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: proto/calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetTaskRequest is an empty request to get a task
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{0}
}

// TaskResponse contains all details about a calculation task
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExpressionId  int32                  `protobuf:"varint,2,opt,name=expression_id,json=expressionId,proto3" json:"expression_id,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	OperationTime int32                  `protobuf:"varint,4,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	// Arg1 can be either a number or a string reference
	//
	// Types that are valid to be assigned to Arg1:
	//
	//	*TaskResponse_NumberArg1
	//	*TaskResponse_StringArg1
	Arg1 isTaskResponse_Arg1 `protobuf_oneof:"arg1"`
	// Arg2 can be either a number or a string reference
	//
	// Types that are valid to be assigned to Arg2:
	//
	//	*TaskResponse_NumberArg2
	//	*TaskResponse_StringArg2
	Arg2          isTaskResponse_Arg2 `protobuf_oneof:"arg2"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskResponse) GetExpressionId() int32 {
	if x != nil {
		return x.ExpressionId
	}
	return 0
}

func (x *TaskResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TaskResponse) GetOperationTime() int32 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *TaskResponse) GetArg1() isTaskResponse_Arg1 {
	if x != nil {
		return x.Arg1
	}
	return nil
}

func (x *TaskResponse) GetNumberArg1() float64 {
	if x != nil {
		if x, ok := x.Arg1.(*TaskResponse_NumberArg1); ok {
			return x.NumberArg1
		}
	}
	return 0
}

func (x *TaskResponse) GetStringArg1() string {
	if x != nil {
		if x, ok := x.Arg1.(*TaskResponse_StringArg1); ok {
			return x.StringArg1
		}
	}
	return ""
}

func (x *TaskResponse) GetArg2() isTaskResponse_Arg2 {
	if x != nil {
		return x.Arg2
	}
	return nil
}

func (x *TaskResponse) GetNumberArg2() float64 {
	if x != nil {
		if x, ok := x.Arg2.(*TaskResponse_NumberArg2); ok {
			return x.NumberArg2
		}
	}
	return 0
}

func (x *TaskResponse) GetStringArg2() string {
	if x != nil {
		if x, ok := x.Arg2.(*TaskResponse_StringArg2); ok {
			return x.StringArg2
		}
	}
	return ""
}

type isTaskResponse_Arg1 interface {
	isTaskResponse_Arg1()
}

type TaskResponse_NumberArg1 struct {
	NumberArg1 float64 `protobuf:"fixed64,5,opt,name=number_arg1,json=numberArg1,proto3,oneof"`
}

type TaskResponse_StringArg1 struct {
	StringArg1 string `protobuf:"bytes,6,opt,name=string_arg1,json=stringArg1,proto3,oneof"`
}

func (*TaskResponse_NumberArg1) isTaskResponse_Arg1() {}

func (*TaskResponse_StringArg1) isTaskResponse_Arg1() {}

type isTaskResponse_Arg2 interface {
	isTaskResponse_Arg2()
}

type TaskResponse_NumberArg2 struct {
	NumberArg2 float64 `protobuf:"fixed64,7,opt,name=number_arg2,json=numberArg2,proto3,oneof"`
}

type TaskResponse_StringArg2 struct {
	StringArg2 string `protobuf:"bytes,8,opt,name=string_arg2,json=stringArg2,proto3,oneof"`
}

func (*TaskResponse_NumberArg2) isTaskResponse_Arg2() {}

func (*TaskResponse_StringArg2) isTaskResponse_Arg2() {}

// TaskResultRequest sends a calculation result back
type TaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        float64                `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultRequest) Reset() {
	*x = TaskResultRequest{}
	mi := &file_proto_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultRequest) ProtoMessage() {}

func (x *TaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultRequest.ProtoReflect.Descriptor instead.
func (*TaskResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResultRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskResultRequest) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TaskResultRequest) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *TaskResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// TaskResultResponse indicates whether the result was accepted
type TaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultResponse) Reset() {
	*x = TaskResultResponse{}
	mi := &file_proto_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultResponse) ProtoMessage() {}

func (x *TaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultResponse.ProtoReflect.Descriptor instead.
func (*TaskResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_calculator_proto protoreflect.FileDescriptor

const file_proto_calculator_proto_rawDesc = "" +
	"\n" +
	"\x16proto/calculator.proto\x12\n" +
	"calculator\"\x10\n" +
	"\x0eGetTaskRequest\"\xad\x02\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12#\n" +
	"\rexpression_id\x18\x02 \x01(\x05R\fexpressionId\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12%\n" +
	"\x0eoperation_time\x18\x04 \x01(\x05R\roperationTime\x12!\n" +
	"\vnumber_arg1\x18\x05 \x01(\x01H\x00R\n" +
	"numberArg1\x12!\n" +
	"\vstring_arg1\x18\x06 \x01(\tH\x00R\n" +
	"stringArg1\x12!\n" +
	"\vnumber_arg2\x18\a \x01(\x01H\x01R\n" +
	"numberArg2\x12!\n" +
	"\vstring_arg2\x18\b \x01(\tH\x01R\n" +
	"stringArg2B\x06\n" +
	"\x04arg1B\x06\n" +
	"\x04arg2\"\x84\x01\n" +
	"\x11TaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x01R\x06result\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"H\n" +
	"\x12TaskResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa2\x01\n" +
	"\fAgentService\x12?\n" +
	"\aGetTask\x12\x1a.calculator.GetTaskRequest\x1a\x18.calculator.TaskResponse\x12Q\n" +
	"\x10SubmitTaskResult\x12\x1d.calculator.TaskResultRequest\x1a\x1e.calculator.TaskResultResponseB*Z(github.com/neptship/calc-yandex-go/protob\x06proto3"

var (
	file_proto_calculator_proto_rawDescOnce sync.Once
	file_proto_calculator_proto_rawDescData []byte
)

func file_proto_calculator_proto_rawDescGZIP() []byte {
	file_proto_calculator_proto_rawDescOnce.Do(func() {
		file_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)))
	})
	return file_proto_calculator_proto_rawDescData
}

var file_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_calculator_proto_goTypes = []any{
	(*GetTaskRequest)(nil),     // 0: calculator.GetTaskRequest
	(*TaskResponse)(nil),       // 1: calculator.TaskResponse
	(*TaskResultRequest)(nil),  // 2: calculator.TaskResultRequest
	(*TaskResultResponse)(nil), // 3: calculator.TaskResultResponse
}
var file_proto_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.AgentService.GetTask:input_type -> calculator.GetTaskRequest
	2, // 1: calculator.AgentService.SubmitTaskResult:input_type -> calculator.TaskResultRequest
	1, // 2: calculator.AgentService.GetTask:output_type -> calculator.TaskResponse
	3, // 3: calculator.AgentService.SubmitTaskResult:output_type -> calculator.TaskResultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_calculator_proto_init() }
func file_proto_calculator_proto_init() {
	if File_proto_calculator_proto != nil {
		return
	}
	file_proto_calculator_proto_msgTypes[1].OneofWrappers = []any{
		(*TaskResponse_NumberArg1)(nil),
		(*TaskResponse_StringArg1)(nil),
		(*TaskResponse_NumberArg2)(nil),
		(*TaskResponse_StringArg2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculator_proto_goTypes,
		DependencyIndexes: file_proto_calculator_proto_depIdxs,
		MessageInfos:      file_proto_calculator_proto_msgTypes,
	}.Build()
	File_proto_calculator_proto = out.File
	file_proto_calculator_proto_goTypes = nil
	file_proto_calculator_proto_depIdxs = nil
}
